// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBnsVO-ncU8QrO5y9KLnZuBKxPiQno7Ew',
    appId: '1:380248683752:web:60cb5588d0fdb14ca5055d',
    messagingSenderId: '380248683752',
    projectId: 'liftmeup-1c7e2',
    authDomain: 'liftmeup-1c7e2.firebaseapp.com',
    storageBucket: 'liftmeup-1c7e2.appspot.com',
    measurementId: 'G-V5GXP69MJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgFi2Ich1-fgaIBH2FVR10wBbLtVgT6xo',
    appId: '1:380248683752:android:3ee989a9970b5405a5055d',
    messagingSenderId: '380248683752',
    projectId: 'liftmeup-1c7e2',
    storageBucket: 'liftmeup-1c7e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe01YG6aCCB-dp1cIzrpNpezpgcV2-1Uc',
    appId: '1:380248683752:ios:a1119ca03cc04371a5055d',
    messagingSenderId: '380248683752',
    projectId: 'liftmeup-1c7e2',
    storageBucket: 'liftmeup-1c7e2.appspot.com',
    iosClientId: '380248683752-7nnnbhk3il3aojlg50qhml45jek5ksul.apps.googleusercontent.com',
    iosBundleId: 'com.example.liftmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe01YG6aCCB-dp1cIzrpNpezpgcV2-1Uc',
    appId: '1:380248683752:ios:a1119ca03cc04371a5055d',
    messagingSenderId: '380248683752',
    projectId: 'liftmeup-1c7e2',
    storageBucket: 'liftmeup-1c7e2.appspot.com',
    iosClientId: '380248683752-7nnnbhk3il3aojlg50qhml45jek5ksul.apps.googleusercontent.com',
    iosBundleId: 'com.example.liftmeApp',
  );
}
